import { readdir, writeFile } from 'node:fs/promises'
import { relative, resolve, sep } from 'node:path'
import type { Plugin } from 'vite'
import { format } from 'oxfmt'

const ASSET_RE = /\.(png|jpe?g|gif|webp|svg|avif)$/i
const ASSETS_DIR = '-assets' as const

export function routeAssetsPlugin(): Plugin {
  const routesDir = resolve('src/routes')
  const output = resolve('src/route-assets.gen.ts')

  async function generate() {
    const entries: Array<{ routeId: string; assetDir: string; files: string[] }> = []

    async function walk(dir: string) {
      for (const entry of await readdir(dir, { withFileTypes: true })) {
        const path = resolve(dir, entry.name)

        if (!entry.isDirectory()) continue

        if (entry.name === ASSETS_DIR) {
          const files = (await readdir(path, { withFileTypes: true }))
            .filter((e) => e.isFile() && ASSET_RE.test(e.name))
            .map((e) => e.name)
            .sort()

          if (files.length) {
            entries.push({
              routeId: `/${relative(routesDir, dir).replaceAll(sep, '/')}`,
              assetDir: path,
              files,
            })
          }

          continue
        }

        await walk(path)
      }
    }

    await walk(routesDir)

    entries.sort((a, b) => a.routeId.localeCompare(b.routeId))

    const routeTypes = entries.map(({ routeId, files }) => {
      const k = JSON.stringify(`${routeId}/`)
      const v = files.map((f) => `${JSON.stringify(f)}:string`).join('\n')
      return `
        ${k}: {
          ${v}
        }
      `
    })

    const routeGlobs = entries.map(({ routeId, assetDir }) => {
      const globPath = `/${relative(process.cwd(), assetDir).replaceAll(sep, '/')}`
      const k = JSON.stringify(`${routeId}/`)
      const v = JSON.stringify(`${globPath}/*`)
      return `
        ${k}: import.meta.glob<string>(
          ${v}, { eager: true, query: '?url', import: 'default' }
        )
      `
    })

    const formattedOutput = await format(
      output,
      `
      // Generated by route-assets-plugin. Do not edit.

      export interface RouteAssets {
        ${routeTypes.join(',')}
      }

      export const routeAssets = {
        ${routeGlobs.join(',')}
      } as const
    `,
    )

    await writeFile(output, formattedOutput.code)
  }

  return {
    name: 'route-assets',
    buildStart() {
      return generate()
    },
    configureServer(server) {
      const update = (file: string) => {
        if (file.startsWith(routesDir) && file.includes(`${sep}${ASSETS_DIR}${sep}`)) {
          void generate()
        }
      }

      server.watcher.on('add', update)
      server.watcher.on('unlink', update)
    },
  }
}
