catalogMode: strict
cleanupUnusedCatalogs: true

packages:
  - .
allowBuilds:
  esbuild: true
  '@clerk/shared': false
  '@parcel/watcher': false
  bufferutil: false
  core-js: false
  msw: false
  utf-8-validate: false
  'convex-solidjs@https://codeload.github.com/msviderok/convex-solidjs/tar.gz/b21f6332498bcac8b2b2a18bfe2ae78a0402bcc2': true
catalog:
  '@clerk/backend': ^3.12.0
  '@clerk/ui': ^1.25.6
  '@convex-dev/crons': ^0.2.2
  '@dnd-kit/abstract': 0.5.0
  '@dnd-kit/dom': 0.5.0
  '@dnd-kit/solid': 0.5.0
  '@msviderok/base-ui-solid': 1.0.0-beta.12
  '@posthog/convex': ^2.0.32
  '@solid-primitives/scheduled': ^1.5.3
  '@t3-oss/env-core': ^0.13.10
  '@tailwindcss/typography': ^0.5.20
  '@tailwindcss/vite': ^4.3.3
  '@tanstack/solid-router': ^1.170.17
  '@tanstack/solid-start': ^1.168.32
  '@total-typescript/ts-reset': ^0.6.1
  '@types/howler': ^2.2.13
  '@types/node': ^26.1.1
  '@web-kits/audio': ^0.1.0
  class-variance-authority: ^0.7.1
  clerk-solidjs-tanstack-start: ^0.0.3
  clsx: ^2.1.1
  convex: ^1.42.3
  convex-helpers: ^0.1.120
  date-fns: ^4.4.0
  howler: ^2.2.4
  knip: ^6.27.0
  lucide-solid: ^1.25.0
  motion: ^12.42.2
  nitro: 3.0.260610-beta
  oxfmt: ^0.59.0
  oxlint: ^1.74.0
  posthog-js: ^1.405.3
  shadcn: ^4.13.1
  solid-js: 1.9.14
  solid-motionone: ^1.0.4
  svix: ^1.98.0
  tailwind-merge: ^3.6.0
  tailwindcss: ^4.3.3
  tw-animate-css: ^1.4.0
  typescript: ^7.0.2
  valibot: ^1.4.2
  vite: ^8.1.5
  vite-plugin-solid: 2.11.13
minimumReleaseAgeExclude:
  - '@clerk/backend@3.12.0'
  - '@clerk/localizations@4.13.6'
  - '@clerk/shared@4.25.6'
  - '@clerk/ui@1.25.6'
