// Generated by route-assets-plugin. Do not edit.

export interface RouteAsset {
  name: string
  src: string
  size: { width: number; height: number }
}

const globPaths = {
  '//': import.meta.glob<string>('/src/routes/-assets/*', { eager: true, query: '?url', import: 'default' }),
  '/_authed/': import.meta.glob<string>('/src/routes/_authed/-assets/*', {
    eager: true,
    query: '?url',
    import: 'default',
  }),
  '/_authed/application/': import.meta.glob<string>('/src/routes/_authed/application/-assets/*', {
    eager: true,
    query: '?url',
    import: 'default',
  }),
  '/_authed/main/': import.meta.glob<string>('/src/routes/_authed/main/-assets/*', {
    eager: true,
    query: '?url',
    import: 'default',
  }),
  '/_authed/pet/': import.meta.glob<string>('/src/routes/_authed/pet/-assets/*', {
    eager: true,
    query: '?url',
    import: 'default',
  }),
  '/_authed/tour/': import.meta.glob<string>('/src/routes/_authed/tour/-assets/*', {
    eager: true,
    query: '?url',
    import: 'default',
  }),
} as const

export const assets = {
  '//': {
    'bg_pattern.png': {
      name: 'bg_pattern.png',
      size: { width: 400 as number, height: 400 as number },
      src: globPaths['//']['/src/routes/-assets/bg_pattern.png']!,
    },
  },
  '/_authed/': {
    'hats.png': {
      name: 'hats.png',
      size: { width: 1360 as number, height: 80 as number },
      src: globPaths['/_authed/']['/src/routes/_authed/-assets/hats.png']!,
    },
  },
  '/_authed/application/': {
    'BG.png': {
      name: 'BG.png',
      size: { width: 2043 as number, height: 1144 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/BG.png']!,
    },
    'bg_town.png': {
      name: 'bg_town.png',
      size: { width: 576 as number, height: 324 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/bg_town.png']!,
    },
    'boxes.png': {
      name: 'boxes.png',
      size: { width: 1463 as number, height: 1563 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/boxes.png']!,
    },
    'c_asset_ladder.png': {
      name: 'c_asset_ladder.png',
      size: { width: 67 as number, height: 335 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/c_asset_ladder.png']!,
    },
    'c_asset_normal.png': {
      name: 'c_asset_normal.png',
      size: { width: 221 as number, height: 336 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/c_asset_normal.png']!,
    },
    'c_asset_slim.png': {
      name: 'c_asset_slim.png',
      size: { width: 125 as number, height: 335 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/c_asset_slim.png']!,
    },
    'c_asset_wide.png': {
      name: 'c_asset_wide.png',
      size: { width: 304 as number, height: 335 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/c_asset_wide.png']!,
    },
    'hog_donotcross.png': {
      name: 'hog_donotcross.png',
      size: { width: 855 as number, height: 944 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/hog_donotcross.png']!,
    },
    'hog_drill.png': {
      name: 'hog_drill.png',
      size: { width: 1168 as number, height: 617 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/hog_drill.png']!,
    },
    'hog_noting.png': {
      name: 'hog_noting.png',
      size: { width: 909 as number, height: 1066 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/hog_noting.png']!,
    },
    'hog_truck.png': {
      name: 'hog_truck.png',
      size: { width: 1476 as number, height: 949 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/hog_truck.png']!,
    },
    'pilar.png': {
      name: 'pilar.png',
      size: { width: 320 as number, height: 64 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/pilar.png']!,
    },
    'truck_wheel.png': {
      name: 'truck_wheel.png',
      size: { width: 196 as number, height: 197 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/truck_wheel.png']!,
    },
  },
  '/_authed/main/': {
    'application.png': {
      name: 'application.png',
      size: { width: 820 as number, height: 580 as number },
      src: globPaths['/_authed/main/']['/src/routes/_authed/main/-assets/application.png']!,
    },
    'experience.png': {
      name: 'experience.png',
      size: { width: 281 as number, height: 313 as number },
      src: globPaths['/_authed/main/']['/src/routes/_authed/main/-assets/experience.png']!,
    },
    'intro.png': {
      name: 'intro.png',
      size: { width: 900 as number, height: 580 as number },
      src: globPaths['/_authed/main/']['/src/routes/_authed/main/-assets/intro.png']!,
    },
    'main.png': {
      name: 'main.png',
      size: { width: 4096 as number, height: 732 as number },
      src: globPaths['/_authed/main/']['/src/routes/_authed/main/-assets/main.png']!,
    },
    'main_empty.png': {
      name: 'main_empty.png',
      size: { width: 4096 as number, height: 732 as number },
      src: globPaths['/_authed/main/']['/src/routes/_authed/main/-assets/main_empty.png']!,
    },
    'personal.png': {
      name: 'personal.png',
      size: { width: 860 as number, height: 580 as number },
      src: globPaths['/_authed/main/']['/src/routes/_authed/main/-assets/personal.png']!,
    },
    'pet.png': {
      name: 'pet.png',
      size: { width: 264 as number, height: 312 as number },
      src: globPaths['/_authed/main/']['/src/routes/_authed/main/-assets/pet.png']!,
    },
    'sign.png': {
      name: 'sign.png',
      size: { width: 275 as number, height: 74 as number },
      src: globPaths['/_authed/main/']['/src/routes/_authed/main/-assets/sign.png']!,
    },
    'temp1.png': {
      name: 'temp1.png',
      size: { width: 193 as number, height: 196 as number },
      src: globPaths['/_authed/main/']['/src/routes/_authed/main/-assets/temp1.png']!,
    },
    'temp1_with_table.png': {
      name: 'temp1_with_table.png',
      size: { width: 224 as number, height: 328 as number },
      src: globPaths['/_authed/main/']['/src/routes/_authed/main/-assets/temp1_with_table.png']!,
    },
    'temp2.png': {
      name: 'temp2.png',
      size: { width: 318 as number, height: 353 as number },
      src: globPaths['/_authed/main/']['/src/routes/_authed/main/-assets/temp2.png']!,
    },
  },
  '/_authed/pet/': {
    'bg.png': {
      name: 'bg.png',
      size: { width: 3200 as number, height: 1920 as number },
      src: globPaths['/_authed/pet/']['/src/routes/_authed/pet/-assets/bg.png']!,
    },
    'climber.png': {
      name: 'climber.png',
      size: { width: 534 as number, height: 876 as number },
      src: globPaths['/_authed/pet/']['/src/routes/_authed/pet/-assets/climber.png']!,
    },
    'stander.png': {
      name: 'stander.png',
      size: { width: 646 as number, height: 711 as number },
      src: globPaths['/_authed/pet/']['/src/routes/_authed/pet/-assets/stander.png']!,
    },
  },
  '/_authed/tour/': {
    'evolution.png': {
      name: 'evolution.png',
      size: { width: 2324 as number, height: 698 as number },
      src: globPaths['/_authed/tour/']['/src/routes/_authed/tour/-assets/evolution.png']!,
    },
    'podium.png': {
      name: 'podium.png',
      size: { width: 2324 as number, height: 437 as number },
      src: globPaths['/_authed/tour/']['/src/routes/_authed/tour/-assets/podium.png']!,
    },
    'shadow.png': {
      name: 'shadow.png',
      size: { width: 351 as number, height: 71 as number },
      src: globPaths['/_authed/tour/']['/src/routes/_authed/tour/-assets/shadow.png']!,
    },
    'stage1.png': {
      name: 'stage1.png',
      size: { width: 420 as number, height: 374 as number },
      src: globPaths['/_authed/tour/']['/src/routes/_authed/tour/-assets/stage1.png']!,
    },
    'stage2.png': {
      name: 'stage2.png',
      size: { width: 410 as number, height: 420 as number },
      src: globPaths['/_authed/tour/']['/src/routes/_authed/tour/-assets/stage2.png']!,
    },
    'stage3.png': {
      name: 'stage3.png',
      size: { width: 440 as number, height: 480 as number },
      src: globPaths['/_authed/tour/']['/src/routes/_authed/tour/-assets/stage3.png']!,
    },
    'stage4.png': {
      name: 'stage4.png',
      size: { width: 480 as number, height: 480 as number },
      src: globPaths['/_authed/tour/']['/src/routes/_authed/tour/-assets/stage4.png']!,
    },
  },
} as const

export type Assets = typeof assets
