// Generated by route-assets-plugin. Do not edit.

export interface RouteAsset {
  name: string
  src: string
  size: { width: number; height: number }
}

const globPaths = {
  '/_authed/application/': import.meta.glob<string>('/src/routes/_authed/application/-assets/*', {
    eager: true,
    query: '?url',
    import: 'default',
  }),
  '/_authed/main/': import.meta.glob<string>('/src/routes/_authed/main/-assets/*', {
    eager: true,
    query: '?url',
    import: 'default',
  }),
  '/_authed/tour/': import.meta.glob<string>('/src/routes/_authed/tour/-assets/*', {
    eager: true,
    query: '?url',
    import: 'default',
  }),
} as const

export const assets = {
  '/_authed/application/': {
    'BG.png': {
      name: 'BG.png',
      size: { width: 2043 as number, height: 1144 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/BG.png']!,
    },
    'bg_town.png': {
      name: 'bg_town.png',
      size: { width: 576 as number, height: 324 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/bg_town.png']!,
    },
    'boxes.png': {
      name: 'boxes.png',
      size: { width: 1463 as number, height: 1563 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/boxes.png']!,
    },
    'c_asset_ladder.png': {
      name: 'c_asset_ladder.png',
      size: { width: 67 as number, height: 335 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/c_asset_ladder.png']!,
    },
    'c_asset_normal.png': {
      name: 'c_asset_normal.png',
      size: { width: 221 as number, height: 336 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/c_asset_normal.png']!,
    },
    'c_asset_slim.png': {
      name: 'c_asset_slim.png',
      size: { width: 125 as number, height: 335 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/c_asset_slim.png']!,
    },
    'c_asset_wide.png': {
      name: 'c_asset_wide.png',
      size: { width: 304 as number, height: 335 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/c_asset_wide.png']!,
    },
    'hog_donotcross.png': {
      name: 'hog_donotcross.png',
      size: { width: 855 as number, height: 944 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/hog_donotcross.png']!,
    },
    'hog_drill.png': {
      name: 'hog_drill.png',
      size: { width: 1168 as number, height: 617 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/hog_drill.png']!,
    },
    'hog_noting.png': {
      name: 'hog_noting.png',
      size: { width: 909 as number, height: 1066 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/hog_noting.png']!,
    },
    'hog_truck.png': {
      name: 'hog_truck.png',
      size: { width: 1476 as number, height: 949 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/hog_truck.png']!,
    },
    'pilar.png': {
      name: 'pilar.png',
      size: { width: 320 as number, height: 64 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/pilar.png']!,
    },
    'truck_wheel.png': {
      name: 'truck_wheel.png',
      size: { width: 196 as number, height: 197 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/truck_wheel.png']!,
    },
  },
  '/_authed/main/': {
    'main.png': {
      name: 'main.png',
      size: { width: 4096 as number, height: 732 as number },
      src: globPaths['/_authed/main/']['/src/routes/_authed/main/-assets/main.png']!,
    },
  },
  '/_authed/tour/': {
    'evolution.png': {
      name: 'evolution.png',
      size: { width: 2324 as number, height: 698 as number },
      src: globPaths['/_authed/tour/']['/src/routes/_authed/tour/-assets/evolution.png']!,
    },
  },
} as const

export type Assets = typeof assets
