// Generated by route-assets-plugin. Do not edit.

export interface RouteAsset {
  name: string
  src: string
  size: { width: number; height: number }
}

const globPaths = {
  '/_authed/application/': import.meta.glob<string>('/src/routes/_authed/application/-assets/*', {
    eager: true,
    query: '?url',
    import: 'default',
  }),
} as const

export const assets = {
  '/_authed/application/': {
    'c_asset_ladder_67x335.png': {
      name: 'c_asset_ladder_67x335.png',
      size: { width: 67 as number, height: 335 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/c_asset_ladder_67x335.png']!,
    },
    'c_asset_normal_221x336.png': {
      name: 'c_asset_normal_221x336.png',
      size: { width: 221 as number, height: 336 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/c_asset_normal_221x336.png']!,
    },
    'c_asset_slim_125x335.png': {
      name: 'c_asset_slim_125x335.png',
      size: { width: 125 as number, height: 335 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/c_asset_slim_125x335.png']!,
    },
    'c_asset_wide_304x335.png': {
      name: 'c_asset_wide_304x335.png',
      size: { width: 304 as number, height: 335 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/c_asset_wide_304x335.png']!,
    },
    'hog_donotcross_2979x1667.png': {
      name: 'hog_donotcross_2979x1667.png',
      size: { width: 2979 as number, height: 1667 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/hog_donotcross_2979x1667.png']!,
    },
    'hog_drill_2979x1667.png': {
      name: 'hog_drill_2979x1667.png',
      size: { width: 2979 as number, height: 1667 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/hog_drill_2979x1667.png']!,
    },
    'hog_noting_2979x1667.png': {
      name: 'hog_noting_2979x1667.png',
      size: { width: 2979 as number, height: 1667 as number },
      src: globPaths['/_authed/application/']['/src/routes/_authed/application/-assets/hog_noting_2979x1667.png']!,
    },
  },
} as const
