// Generated by route-assets-plugin. Do not edit.

export interface RouteAssets {
  "/_authed/application/": {
    "c_asset_ladder.png": string;
    "c_asset_normal.png": string;
    "c_asset_slim.png": string;
    "c_asset_wide.png": string;
    "hog_donotcross.png": string;
    "hog_drill.png": string;
    "hog_noting.png": string;
  };
}

export const routeAssets = {
  "/_authed/application/": import.meta.glob<string>("/src/routes/_authed/application/-assets/*", {
    eager: true,
    query: "?url",
    import: "default",
  }),
} as const;
